spring:
  application:
    name: wms-tenant-service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  # MongoDB Configuration for Central Database
  data:
    mongodb:
      # Full URI including database name - exactly like LTR-Backend
      uri: ${MONGODB_URI:mongodb://flybizdigi:FlyBizDigi%40123@cloud.leadtorev.com:27170/wms_pro_tenants?authSource=admin&readPreference=primary}
      auto-index-creation: true

  # Cache Configuration
  cache:
    type: caffeine
    cache-names: tenantMappings
    caffeine:
      spec: maximumSize=100,expireAfterWrite=10m

  # Jackson Configuration
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
      indent-output: true
    deserialization:
      fail-on-unknown-properties: false
    time-zone: UTC

server:
  port: ${SERVER_PORT:6010}
  error:
    include-message: always
    include-binding-errors: always
  servlet:
    context-path: /

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:6000/eureka/}
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 30
    instance-info-replication-interval-seconds: 30
  instance:
    hostname: ${HOSTNAME:localhost}
    instance-id: ${spring.application.name}:${server.port}:${random.value}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    metadata-map:
      service-type: tenant-management
      version: 1.0.0

# Management Endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
  health:
    mongo:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}

# Logging Configuration
logging:
  level:
    root: INFO
    com.wmspro.tenant: DEBUG
    org.springframework.data.mongodb: DEBUG
    com.mongodb: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/wms-tenant-service.log
    max-size: 10MB
    max-history: 30

# API Documentation (Swagger/OpenAPI)
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  show-actuator: true

# Application-specific Configuration
app:
  tenant:
    default-pool-size: 10
    min-pool-size: 2
    connection-timeout-seconds: 10
    max-idle-time-minutes: 10
    service:
      url: ${TENANT_SERVICE_URL:http://localhost:6010}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:3001}
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
    allowed-headers: "*"
    allow-credentials: true
    max-age: 3600

---
# Development Profile
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      uri: mongodb://flybizdigi:FlyBizDigi%40123@cloud.leadtorev.com:27170/wms_pro_tenants?authSource=admin&readPreference=primary
      central-database: wms_pro_tenants

logging:
  level:
    com.wmspro.tenant: DEBUG
    org.springframework.data.mongodb: DEBUG

---
# Production Profile
spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      uri: ${MONGODB_URI}
      central-database: ${CENTRAL_DB_NAME:wms_pro_tenants}

logging:
  level:
    com.wmspro.tenant: INFO
    org.springframework.data.mongodb: WARN

server:
  port: ${SERVER_PORT:6010}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}